{
 "title": "Solar Control Program",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Pylontech Battery Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery State of Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT\n  ts AS \"time\",\n  device_name AS metric,\n  soc\nFROM\n  pylontech_bms\nWHERE\n  $__timeFilter(ts)\nORDER BY\n  ts"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT ts AS \"time\", device_name AS \"Battery\", b_status AS \"Battery Status\", v_status AS \"BMS Voltage Status\", c_status AS \"BMS CurrentStatus\", t_status AS \"BMS Temperature Status\" FROM pylontech_bms WHERE (device_name, ts) IN (SELECT device_name, MAX(ts) FROM pylontech_bms GROUP BY device_name)"
    }
   ]
  },
  {
   "title": "Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT ts AS \"time\", device_name AS metric, soc FROM pylontech_bms WHERE $__timeFilter(ts) ORDER BY ts"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT ts AS \"time\", device_name AS metric, temperature FROM pylontech_bms WHERE $__timeFilter(ts) ORDER BY ts"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT ts AS \"time\", device_name AS metric, voltage FROM pylontech_bms WHERE $__timeFilter(ts) ORDER BY ts"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT ts AS \"time\", device_name AS metric, current FROM pylontech_bms WHERE $__timeFilter(ts) ORDER BY ts"
    }
   ]
  },
  {
   "title": "Conext Inverter Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Information",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ts AS \"time\",\n  -grid_power AS \"Grid Power\",\n  load_power AS \"Load Power\",\n  inverter_dc_power AS \"Inverter Power\"\nFROM\n  conext_xw\nWHERE\n  $__timeFilter(ts)\nORDER BY\n  ts"
      }
     ]
    },
    {
     "title": "Inverter Status",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "dataset": "scpdata",
       "rawSql": "SELECT inverter_status AS \"Operation Mode\",\n inverter_load_shave_status AS \"Load Shave Status\",\n inverter_grid_support_status AS \"Grid Support Status\",\n inverter_active_warnings_status AS \"Active Warnings\",\n inverter_active_faults_status AS \"Active Faults\"\nFROM conext_xw\nWHERE (ts) IN (SELECT MAX(ts) from conext_xw)"
      }
     ]
    },
    {
     "title": "Inverter Information",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "dataset": "scpdata",
       "rawSql": "SELECT energy_load_month AS \"Monthly Energy Used\",\n energy_grid_month AS \"Monthly Energy from Grid\",\n energy_battery_month AS \"Monthly Energy from Solar\",\n battery_low_voltage AS \"Battery Low Voltage  Cutout\",\n battery_hysteresis AS \"Battery Voltage Hysteresis\" \n FROM conext_xw\n WHERE (ts) IN (SELECT MAX(ts) FROM conext_xw)"
      }
     ]
    },
    {
     "title": "Power Information",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT ts AS \"time\", grid_power AS \"Grid Power\", load_power AS \"Load Power\", inverter_dc_power AS \"Inverter Power\" FROM conext_xw WHERE $__timeFilter(ts) ORDER BY ts"
      }
     ]
    },
    {
     "title": "Inverter Current Information",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "rawSql": "SELECT ts AS \"time\",\n grid_current AS \"Grid AC Current\",\n  load_Current AS \"Load AC Current\",\n   inverter_dc_current AS \"Inverter DC Current\"\nFROM conext_xw WHERE $__timeFilter(ts) ORDER BY ts"
      }
     ]
    },
    {
     "title": "Inverter Voltage Information",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "rawSql": "SELECT ts AS \"time\",\n grid_voltage AS \"Grid AC Voltage\",\n  load_voltage AS \"Load AC Voltage\"\nFROM conext_xw WHERE $__timeFilter(ts) ORDER BY ts"
      }
     ]
    }
   ]
  },
  { "title": "Conext MPPT Solar Charger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "PV Power Information",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  device_name AS metric,\n  dc_output_power AS \"PV Power\"\nFROM\n  conext_mppt\nWHERE\n  (device_name) IN ('MPPT: West')\n  AND \n  (ts) IN (\n    SELECT\n      MAX(ts)\n    FROM\n      conext_mppt\n  )"
    },
    {
     "rawSql": "SELECT\n  device_name AS metric,\n  dc_output_power AS \"PV Power\"\nFROM\n  conext_mppt\nWHERE\n  (device_name) IN ('MPPT: East')\n  AND \n  (ts) IN (\n    SELECT\n      MAX(ts)\n    FROM\n      conext_mppt\n  )"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Solar Charge Controller Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT device_name AS metric,\n mppt_status AS \"Operation Mode\",\n mppt_charger_status AS \"Solar Charger Status\",\n mppt_active_warnings_status AS \"Active Warnings\",\n mppt_active_faults_status AS \"Active Faults\"\nFROM conext_mppt\nWHERE (ts) IN (SELECT MAX(ts) from conext_mppt)"
    }
   ]
  },
  {
   "title": "Solar Charge Controller Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT device_name AS metric,\n energy_pv_day AS \"Daily Energy from PV\",\n energy_pv_week AS \"Weekly Energy from PV\",\n energy_pv_month AS \"Monthly Energy from PV\",\n energy_pv_year AS \"Yearly Energy from PV\"\n FROM conext_mppt\n WHERE (ts) IN (SELECT MAX(ts) FROM conext_mppt)"
    }
   ]
  },
  {
   "title": "PV Power Information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT ts AS \"time\",\n device_name AS metric,\n dc_output_power AS \"MPPT: West\"\nFROM conext_mppt WHERE (device_name) IN ('MPPT: West') AND $__timeFilter(ts) ORDER BY ts "
    },
    {
     "rawSql": "SELECT ts AS \"time\",\n device_name AS metric,\n dc_output_power AS \"MPPT: East\"\nFROM conext_mppt WHERE (device_name) IN ('MPPT: East') AND $__timeFilter(ts) ORDER BY ts "
    }
   ]
  },
  {
   "title": "PV Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "scpdata",
     "rawSql": "SELECT\n  ts AS \"time\",\n  device_name AS metric,\n  dc_input_voltage\nFROM\n  conext_mppt\nWHERE\n  $__timeFilter(ts)\nORDER BY\n  ts"
    }
   ]
  }
 ]
}